
import type { Equipment } from './types';

export const EQUIPMENT_LIST: Equipment[] = [
    { name: "Air Compressor 269 cfm", category: "General" },
    { name: "Air Compressor 375 cfm", category: "General" },
    { name: "Ambulance", category: "Vehicles" },
    { name: "Asphalt Cutting Machine", category: "Roadwork" },
    { name: "Backhoe Loader", category: "Earthmoving" },
    { name: "Big Forklift (5-7 Tons)", category: "Lifting" },
    { name: "Boom Truck", category: "Lifting" },
    { name: "Distribution Board 1200 kva", category: "Power" },
    { name: "Distribution Board 2500 KVA", category: "Power" },
    { name: "Double Drum Vibratory Roller", category: "Compaction" },
    { name: "Flat Truck 3-4 Tons", category: "Vehicles" },
    { name: "Flat Truck 3-4 Tons (Small Dump Truck)", category: "Vehicles" },
    { name: "Generator < 10 KVA", category: "Power" },
    { name: "Generator 10 -> 20 KVA", category: "Power" },
    { name: "Generator 200 -> 250 KVA", category: "Power" },
    { name: "Generator 30 -> 50 KVA", category: "Power" },
    { name: "Generator 375 -> 450 KVA", category: "Power" },
    { name: "Generator 500 KVA", category: "Power" },
    { name: "Generator 600 KVA", category: "Power" },
    { name: "Generator 60 -> 80 KVA", category: "Power" },
    { name: "Generator 90 -> 120 KVA", category: "Power" },
    { name: "Generator 130 -> 160 KVA", category: "Power" },
    { name: "Hydraulic Excavator", category: "Earthmoving" },
    { name: "Hydraulic Jack Hammer", category: "Demolition" },
    { name: "Jack Hammer Pneumatic", category: "Demolition" },
    { name: "Light Tower", category: "General" },
    { name: "Lighting Balloon - Covered Area <8000M2", category: "General" },
    { name: "Manlift (Working Height 24m to 30m)", category: "Lifting" },
    { name: "Metal Tank", category: "General" },
    { name: "Mini-Forklift (2-3 Tons)", category: "Lifting" },
    { name: "Mobile Crane 120-140 Tons", category: "Lifting" },
    { name: "Mobile Crane 40-60 Tons", category: "Lifting" },
    { name: "Mobile Crane 70-90 Tons", category: "Lifting" },
    { name: "Motor Grader", category: "Earthmoving" },
    { name: "Power Trowel", category: "Concrete" },
    { name: "Rammer", category: "Compaction" },
    { name: "Road Truck Tractor", category: "Vehicles" },
    { name: "Scissor Lift (10-14M)", category: "Lifting" },
    { name: "Skid Steer Loader", category: "Earthmoving" },
    { name: "Tandem Vibratory Roller", category: "Compaction" },
    { name: "Tank Truck (Big)", category: "Vehicles" },
    { name: "Telehandler", category: "Lifting" },
    { name: "Tipper Trailer", category: "Vehicles" },
    { name: "Tower Crane Flat Top (12-16 Tons) with Climbing Cage", category: "Lifting" },
    { name: "Tower Crane High Top (12-16 Tons)", category: "Lifting" },
    { name: "Tower Crane High Top (8-10 Tons)", category: "Lifting" },
    { name: "Vibrating Plate", category: "Compaction" },
    { name: "Wheel Loader", category: "Earthmoving" },
    { name: "Bulldozer", category: "Earthmoving" },
    { name: "Crawler Excavator", category: "Earthmoving" },
    { name: "Dragline Excavator", category: "Earthmoving" },
    { name: "Front Loader", category: "Earthmoving" },
    { name: "Paver", category: "Roadwork" },
    { name: "Concrete Pump", category: "Concrete" },
    { name: "Crawler Crane", category: "Lifting" },
    { name: "Rough Terrain Crane", category: "Lifting" },
    { name: "Dump Truck", category: "Vehicles" },
    { name: "Scraper", category: "Earthmoving" },
    { name: "Trencher", category: "Earthmoving" },
    { name: "Articulated Hauler", category: "Vehicles" },
    { name: "Pipe Layer", category: "General" },
    { name: "Pile Driver", category: "Construction" },
    { name: "Soil Compactor", category: "Compaction" },
    { name: "Asphalt Paver", category: "Roadwork" },
    { name: "Concrete Mixer Truck", category: "Concrete" },
    { name: "Material Handler", category: "Lifting" },
    { name: "Rock Breaker", category: "Demolition" },
    { name: "Wheel Tractor Scraper", category: "Earthmoving" },
];
